### ISSUE TITLE
Documentation - Requirement Specification

### ISSUE THREAD

**Issue by OOHQ3E** [ekeamiowner/AMI#1]
# This documentation has 10 parts: 

- [x] #6
- [x] #5
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14

More people can take this issue and do the part they'd like.

Pdf for help: http://aries.ektf.hu/~tajti/rft-afp/AFP_v2.pdf

**Comment by rezlevi** [comment]
Review all of them, then close this issue
