### ISSUE TITLE
Built-in login and register package

### ISSUE THREAD

**Issue by vamosmarton** [ekeamiowner/AMI#159]
- Nézz utána a laravel breeze package-nek
- Hogyan lehet behúzni már meglévő projektbe? (más mint, ha egy újonnan generált laravel projektnél húzod be, mert itt figyelni kell a meglévő user táblára és modelre, illetve a routeokra (a web.php teljes tartalmára))
- Előre tesztelésként ajánlott egy új projektben kipróbálni
- Saját branchen dolgozz

Kiindulási segítség hozzá [itt](https://www.youtube.com/watch?v=f1hCx-NXbek).

**Comment by Csasziuser** [comment]
https://docs.google.com/document/d/1rn-6pfqccsUMGrYDMewYM9tfNkTAZvuXOgL04EyHDlw/edit?usp=sharing
