### ISSUE TITLE
Navbar fix

### ISSUE THREAD

**Issue by vamosmarton** [ekeamiowner/AMI#160]
- [x] Javítani: az első lefelé görgetésnél "ugrik" egyet
- [x] A search funkció ide nem szükséges
- [x] login / logout ikon hozzáadása a szövegek helyett
- [x] Megoldani minden oldalon úgy, mint a /login és /register oldalakon, hogy a headerhez hozzá "tapad" a navbar

Ezeket a feladatokat külön is lehet szervezni issuekra és külön megoldani

**Comment by MizereRobin** [comment]
https://docs.google.com/document/d/1a3HVds8x6VgcQi2P6NizKkRDN_-bzCxz/edit?usp=sharing&ouid=102475829055382389804&rtpof=true&sd=true
