### ISSUE TITLE
Article revision page

### ISSUE THREAD

**Issue by vamosmarton** [ekeamiowner/AMI#171]
A feladathoz akár több ember is javasolt
Ez a nézet felelős a kiválasztott cikk bírálásáért
- A Editor page oldalon a Revision gombra kattintva megjelenik a kiválaszott cikk (show) nézete, rajta a cikk tulajdonságaival, ahol a bíráló kiválaszthatja a cikk státuszát (SUBMITTED, ACCEPTED, REJECTED, UNDER_REVIEW)
- Az Article revision page nézeten (az aktuális cikken) legyen egy Submit gomb ami jóváhagyja a status változtatását
- Ha a Submit gomb megnyomása után, az article a REJECTED/ACCEPTED státuszba került, akkor növeli a user tábla completed_review mezőjét
- A Submit gomb akkor fetchel a revisions és reviews táblákba, ha a SUBMITTED statuson kívűl bármelyik másik állapotba került

További megjegyezés:
A gomb és az útvonal összekapcsolását később is meglehet oldani, a párhuzamos munkára tekintettel, így nem kell megvárni, amíg elkészül a teljes Editor page
Általában a revision és a reviews két külön dolog, de most az egyszerűség kedvéért a fetchelés automatikusan történhet a először a revisions táblába majd a reviews táblába

**Comment by PenyiDavid** [comment]
[Teszt jegyzőkönyv.docx](https://github.com/ekeamiowner/AMI/files/15286875/Teszt.jegyzokonyv.docx)
